### ISSUE TITLE
What license is this code published under?

### ISSUE THREAD

**Issue by analog-cbarber** [awesomebytes/parametric_modeling#2]
Did you intend this to just be public domain or are there any restrictions on reuse?

**Comment by awesomebytes** [comment]
Public domain. But note that some code is VERY inspired in the MATLAB
version. I wasn't, and I am not that sure which license to apply. I tend to
make it all BSD. But I do not know the possible consequences of the
similarity of some of these code pieces (intended as this is expected to be
a replacement in Python of the Matlab utilities).

Any idea/proposal?

**Comment by analog-cbarber** [comment]
You have some commented out MATLAB code with MathWorks copyrights in it. Unless that code has an appropriate open source license you may be violating the copyright if you include it.

I would think that if you have mechanically translated MathWorks code, that the resulting product would probably be considered to be MathWork's intellectual property. If instead you only used the MathWorks code to understand the algorithm and reimplemented it in a pythonic (or numpythonic) fashion, then it is probably ok.

You are going to need to carefully go through the code to figure out what the situation is.

**Comment by awesomebytes** [comment]
I clearly state where it comes from (MatlabTM, and with the information of
the authors of every function if it was there).

The code was partially generated and then fixed or coded from scratch by
hand depending on the file. This was done 5 years ago so I don't remember
anymore.

This repo was an exercise for university. I won't dedicate much time to it,
really (I haven't used it again). If anyone plans to make commercial use of
it... I wouldn't recommend it. (The code isn't very pythonic either).

**Comment by analog-cbarber** [comment]
Including a Matlab trademark does not give you the right to include their code in your repository unless their license allows it, which may or may not be the case. Furthermore, their license could impose restrictions on your license.

In any case, you answered my question: basically, it is ok to reuse this code in so far as it does not violate MathWork's copyright and license. Use at your own risk!

**Comment by chummersone** [comment]
Once the copyright issues are resolved, can you please add a license? [It's not hard]( https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository). Failure to specify a license is not helpful, since according to [GitHub](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by awesomebytes** [comment]
I added a LICENSE file and a note on the README. Anything I wrote is BSD. What happens to the MATLAB pieces stays in doubt of what can be done with it. I won't research it further, if anyone wants to use it, it's up to them to decide.

**Comment by chummersone** [comment]
Thanks very much!

**Comment by awesomebytes** [comment]
Have a good one!
